### ISSUE TITLE
REF:  Creating internal hrefs in shiny apps

### ISSUE THREAD

**Issue by TahorSuiJuris** [davidruvolo51/shinyAppTutorials#1]
Using your wonderful code as an example, the links are not working.

**Comment by TahorSuiJuris** [comment]
Used your code to study, but the links are not working.

**Comment by davidruvolo51** [comment]
Hi @TahorSuiJuris , 

Sorry, for the delay in reply. I haven't checked the issues page in a while (very long time). Are you experiencing issues with the links? Were the issues occurring on the GitHub docs or the blog? I have worked on the site over the last few months and have hopefully fixed broken links.

- David
