### ISSUE TITLE
Using the customHref JS function within different modules

### ISSUE THREAD

**Issue by AdamLaang** [davidruvolo51/shinyAppTutorials#25]
Hi David! 

Thank you for a great tutorial about internal links using tags$a with customHref, the app example simplified the example a lot. 

However, I'm currently working on a bigger project and have therefore included golem and working within different modules.
I'm still a rookie so I can't really figure out where to implement the JS when dealing with different modules.

In the following code I'm calling the script from the module that handles the different tabPanels. 

```
 mod_main_page_v2_ui <- function(id){
   ns <- NS(id)
   tagList(
     tags$head(
       tags$script(src = "www/tab_ref.js")
     ),

    navbarPage(id = ns("navbar"), title = actionLink(ns("title"), tags$i(class = "fa fa-home", `aria-hidden`="true"), type = "heading"),
               position = "fixed-top",
               collapsible = TRUE, selected = " ",
               tabPanel("Tools", mod_Columns_ui(ns("Columns_ui_1"))),
               tabPanel("Visualization", mod_visual_ui(ns("visual_ui_1"))),
                tabPanel("Database",
                            tabsetPanel(
                            tabPanel("Input objects", mod_input_overview_ui(ns("input_overview_ui_1"))),
                            tabPanel("Module objects", mod_module_overview_ui(ns("module_overview_ui_1"))),
                            tabPanel("Enrichment objects", mod_enrichment_overview_ui(ns("enrichment_overview_ui_1"))),
                            tabPanel("PPI networks", mod_ppi_networks_ui(ns("ppi_networks_ui_1")))
                 )),
               tabPanel("User guide", value = "user_guide", mod_user_guide_ui(ns("user_guide_ui_1"))),
               tabPanel(" ", mod_welcoming_page_ui(ns("welcoming_page_ui_1")))

```
Now, I need to link back to the tabPanel called "User guide" with value = "user_guide" within a different module:

```
mod_upload_ui <- function(id){
  ns <- NS(id)
  tagList(
    fileInput(ns("expression_matrix"), 
              label = "Upload an expression matrix",
              accept = c("text/csv", "text/plain", "application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "text/tab-separated-values", ".rds"),
              popup = tags$a("Read more about how to upload your data", onclick = "customHref('user_guide');")),
    uiOutput(ns("sample_chooser")),
    htmlOutput(ns("error_name_js"))
  )
```

I'm calling the onclick within a tooltip in the fileInput that is within a different module (I've enabled HTML within the tooltip). Now this simply doesn't work and I think the different modules is causing an issue here. Do you have any good solution for this when working within different modules? 

Sorry for the nonreproducible example! 

Best regards,
Adam

**Comment by AdamLaang** [comment]
I solved it, sorry about that! 

The JS works fine even when dealing with different modules. The problem is within the tooltip, it doesn't allow the javascript. However if I run a basic HTML output within shiny it works just fine.

Best regards,
Adam

**Comment by davidruvolo51** [comment]
Thanks for your message. Glad to hear the issue was resolved!

I'll be updating this example in the near future. There are some accessibility concerns as href attribute is removed and this may cause issues with public facing applications. I think a custom UI component and input binding would be a better approach as it would be easier to use. 

Stay tuned!

**Comment by davidruvolo51** [comment]
I added a new example on creating links. This addresses several issues with the `customHref` function. Check it out here: https://github.com/davidruvolo51/shinyAppTutorials/tree/prod/shiny-links

**Comment by AdamLaang** [comment]
This is great, exactly what I need! 

Thanks a lot!
